//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHeroes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
       
        public int CharacterID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsHero { get; set; }
        public Nullable<bool> IsVillan { get; set; }
    }
}
